### ISSUE TITLE
Add functionality for numbers and special characters which have morse code

### ISSUE THREAD

**Issue by Keshav1105** [acmpesuecc/Morse#2]
As per international Morse code a lot of numbers and characters are not added and cannot be interpreted.

**Comment by HackerGlory** [comment]
please assign me to this

**Comment by ankitam389** [comment]
can i pleeease get assigned to this task??

**Comment by KunalMaverick** [comment]
can i get this assigned to me ??

**Comment by Alley2717** [comment]
can i try

**Comment by tejas-techstack** [comment]
please assign me to this issue

**Comment by diishanbhag** [comment]
please assign this to me

**Comment by Rohit221103** [comment]
can i please get assigned to this issue

**Comment by ManushriJ** [comment]
can i get assigned
